# Generated by Django 4.1.3 on 2022-11-12 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('higherx', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdetails',
            name='username',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
