# Generated by Django 4.1.3 on 2022-11-12 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('higherx', '0002_studentdetails_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentdetails',
            name='hiring',
        ),
    ]
