# Generated by Django 4.1.3 on 2022-11-13 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('higherx', '0003_remove_studentdetails_hiring'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentdetails',
            name='education',
        ),
        migrations.RemoveField(
            model_name='studentdetails',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='studentdetails',
            name='interest',
        ),
        migrations.RemoveField(
            model_name='studentdetails',
            name='username',
        ),
    ]
